### PR TITLE
Update composer for Laravel 11

### PR DESCRIPTION
**Pull request by Linedev-Web**

### CODE REVIEW

**Review by khanzadimahdi — APPROVED** [review]

**Comment by khanzadimahdi** [comment]
have you tested it? I received an error from Packagist.

**Comment by sidewaysglance** [comment]
> have you tested it? I received an error from Packagist.

It has not updated on Packagist: https://packagist.org/packages/shetabit/visitor

**Comment by Linedev-Web** [comment]
In reality I thought that it would be enough to just change the version except that name, conflict with the package jenssegers/agent which has a package version too old of 6 years for example :
- mobiledetect/mobiledetectlib

I just did a PR where I had to implement this lib in Visitor, modifying the code to update it.
It's currently working on my serveurliste.com project.

Here's my PR: https://github.com/shetabit/visitor/pull/58

**Comment by sidewaysglance** [comment]
@khanzadimahdi this seems not to be live in packagist still - what was the error, is there anything anyone can do to help?

**Comment by khanzadimahdi** [comment]
Hi @sidewaysglance 
I think `^11.*` is a wrong syntax! will test and do a new release ASAP.

for more details see: https://github.com/shetabit/visitor/pull/57/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R25

**Pull request merged**
